package com.helha.backend.controllers;

import com.helha.backend.application.dto.AuthRequestDto;
import com.helha.backend.application.services.AuthService;
import jakarta.servlet.http.HttpServletResponse;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseCookie;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/auth")
@RequiredArgsConstructor
public class AuthController {

    private final AuthService authService;

    @PostMapping("/register")
    @ResponseStatus(HttpStatus.CREATED)
    public void register(@RequestBody AuthRequestDto dto) {
        authService.register(dto);
    }

    @PostMapping("/login")
    public ResponseEntity<String> login(@RequestBody AuthRequestDto dto, HttpServletResponse response) {

        //retrieve the token generated by the service
        String token = authService.login(dto);

        //we create a secured cookie
        ResponseCookie jwtCookie = ResponseCookie.from("token", token)
                .httpOnly(true)      // Block access to JS (XSS protection)
                .secure(false)       // we put true only in https
                .path("/")           // available for all the routes
                .maxAge(3600)        // expire after 1 hour (3600 seconds)
                .sameSite("Lax")     // Protection against CSRF attacks
                .build();

        //adding the cookie in the response
        response.addHeader(HttpHeaders.SET_COOKIE, jwtCookie.toString());

        // UPDATE: Return the token itself so it can be used in Swagger Authorize
        return ResponseEntity.ok(token);
    }

    // new log out method
    @PostMapping("/logout")
    public ResponseEntity<String> logout(HttpServletResponse response) {

        //we create a cookie to log out with the same name and a "maxAge" at 0
        ResponseCookie deleteCookie = ResponseCookie.from("token", "")
                .httpOnly(true)
                .path("/")
                .maxAge(0) // destroy the cookie instantly
                .build();

        response.addHeader(HttpHeaders.SET_COOKIE, deleteCookie.toString());

        return ResponseEntity.ok("Déconnexion réussie !");
    }
}